// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtFbZxbNgsq9CIPvOSqhcpD-v9bh1ZcrQ',
    appId: '1:516813002448:web:4dbd492e5c2191b410f0d5',
    messagingSenderId: '516813002448',
    projectId: 'todo-simple-task-app',
    authDomain: 'todo-simple-task-app.firebaseapp.com',
    storageBucket: 'todo-simple-task-app.appspot.com',
    measurementId: 'G-QQWT0KPFX1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLiB4uoESt7YXwbdHIyGrqeZw99zZni24',
    appId: '1:516813002448:android:de6e241825578dfa10f0d5',
    messagingSenderId: '516813002448',
    projectId: 'todo-simple-task-app',
    storageBucket: 'todo-simple-task-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkvclznEY_ZnqR9nkz3cEa5OuPH-mclpM',
    appId: '1:516813002448:ios:a1ee346a97cba7db10f0d5',
    messagingSenderId: '516813002448',
    projectId: 'todo-simple-task-app',
    storageBucket: 'todo-simple-task-app.appspot.com',
    iosClientId: '516813002448-enduojpg539k3nadr29n9grec1o7rh6c.apps.googleusercontent.com',
    iosBundleId: 'com.nevoapps.todo2',
  );
}
